version: "3.8"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my5ql_ch1k1o5*
      MYSQL_DATABASE: chikios
      MYSQL_USER: root
      MYSQL_PASSWORD: my5ql_ch1k1o5*
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
